### PR TITLE
Fix spec-interp and ensure its tests pass

### LINKED ISSUE #30: Failing spec interpreter tests
A series of tests are failing in the spec tests:
```    
- test/spec/address.txt
    
- test/spec/align.txt
    
- test/spec/binary.txt
    
- test/spec/block.txt
    
- test/spec/br.txt
    
- test/spec/br_if.txt
    
- test/spec/br_table.txt
    
- test/spec/call.txt
    
- test/spec/call_indirect.txt
    
- test/spec/const.txt
    
- test/spec/custom_section.txt
    
- test/spec/exports.txt
    
- test/spec/float_literals.txt
    
- test/spec/func.txt
    
- test/spec/func_ptrs.txt
    
- test/spec/get_local.txt
    
- test/spec/globals.txt
    
- test/spec/if.txt
    
- test/spec/imports.txt
    
- test/spec/int_literals.txt
    
- test/spec/labels.txt
    
- test/spec/loop.txt
    
- test/spec/memory.txt
    
- test/spec/nop.txt
    
- test/spec/return.txt
    
- test/spec/select.txt
    
- test/spec/set_local.txt
    
- test/spec/start.txt
    
- test/spec/store_retval.txt
    
- test/spec/switch.txt
    
- test/spec/tee_local.txt
    
- test/spec/token.txt
    
- test/spec/type.txt
    
- test/spec/typecheck.txt
    
- test/spec/unreached-invalid.txt
    
- test/spec/utf8-custom-section-id.txt
    
- test/spec/utf8-import-field.txt
    
- test/spec/utf8-import-module.txt
    
- test/spec/utf8-invalid-encoding.txt
```
These do not fail in the clean branch.

### PR DESCRIPTION
**Pull request by Leonardo2718**
To avoid having the JIT interfere with the `spec-interp` tool, it is
unconditionally disabled for this tool. In addition, instance counting
is added to `wabt::jit::JitEnvironment` to ensure the JIT is only
initialized once.

Fixes #30

### CODE REVIEW

**Comment by Leonardo2718** [comment]
Build failures are not related to this change (see #34). This PR is ready for review @aviansie-ben.

File: src/jit/environment.cc [hunk 1]
```diff
@@ -20,13 +20,20 @@
...
 }
 
 JitEnvironment::~JitEnvironment() {
-  shutdownJit();
+  --instance_count_;
+  if (instance_count_ == 0)
+      shutdownJit();
 }
 
+
```
Comment (aviansie-ben) [inline src/jit/environment.cc]: This empty line should be removed.

**Review by aviansie-ben — CHANGES_REQUESTED** [review]

File: src/jit/environment.cc (hunk 1 above)
Comment (Leonardo2718) [reply src/jit/environment.cc]: Not sure how *that* happened 😛 . Fixed.

**Review by aviansie-ben — APPROVED** [review]
LGTM
